import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/common/NavBar";
import { oswald } from "@/components/fonts";
import Footer from "@/components/common/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-[#d0cdc4] text-black " lang="en">
      <body className={`${oswald.className} antialiased flex flex-col min-h-screen bg-[#d0cdc4] justify-between`}>
        <NavBar />
        <div className="bg-[#d0cdc4] text-black p-5 ">
          {children}
        </div>
        <Footer />
        </body>
    </html>
  );
}
